/* The vocabulary of a call: the states it can be in, the ways it can end, and
 * the errors the room can answer with.
 *
 * Every value here is fixed by the protocol, not by this implementation --
 * they travel in bye messages between an ESP32 and an Android phone, so a
 * number invented here would be a number the other end reads as something
 * else. Each block names the file in the JS reference it was taken from, and
 * the numbering is theirs.
 *
 * ------------------------------------------------------------------------
 * Audio only, and why that is not a limitation being apologised for.
 *
 * ESP32-S3-BOX-3B has no camera interface at all -- two Pmod headers and no
 * DVP or MIPI-CSI -- so there is no video to send, and software H.264 decode
 * on an S3 tops out around 320x240 at 10 fps while sharing a core with Opus,
 * AEC, WiFi and LVGL. ASSESSMENT.md section 10.6 has the measurements. So
 * this SDK negotiates one audio m= section and never offers video: audio_only
 * is true on every call it starts and every call it answers.
 *
 * The video-shaped parts of the protocol still have to be understood, because
 * the other end sends them: a phone that starts a video call sends
 * audio_only=false, and this SDK answers it as audio (which the JS reference
 * calls a downgrade and every client supports). What is absent is the ability
 * to produce or display a video track, not the ability to talk to something
 * that has one.
 */

#ifndef WFAV_TYPES_H
#define WFAV_TYPES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "wfc_model.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------- sizing */

/* A call ID is a UUID the caller mints; the JS reference uses 36 characters
 * plus a deployment prefix. */
#define WFAV_CALL_ID_MAX 64

/* The room PIN: six digits, generated by whoever creates the room and
 * repeated in every request against it. */
#define WFAV_PIN_MAX 16

/* How many other people one call can hold.
 *
 * The protocol allows 16 for audio (MAX_AUDIO_PARTICIPANT_COUNT in
 * avenginekit.js), and the room is created asking for that many so a phone
 * joining later is not turned away. This is the smaller number: how many the
 * BOARD tracks.
 *
 * In this build only one of the slots is ever filled. A group invite is
 * refused before a session exists (wfav_engine.c), so a call is one remote
 * participant, one publisher and one subscriber -- which is also esp_peer's
 * own figure for an S3, two concurrent peers (ASSESSMENT.md 10.3). Each
 * further participant would cost another PeerConnection with its own DTLS
 * session and jitter buffer, and the internal SRAM for a third of those is
 * not there.
 *
 * So 4 is headroom for the bookkeeping, not a supported participant count: a
 * room event may name more feeds than a 1v1 call has, and this array is where
 * they land. Anything that made group calls answerable has to revisit the
 * memory question first, not just this number. */
#define WFAV_MAX_PARTICIPANTS 4

/* ------------------------------------------------------------ call state */

/* callState.js. A call is in exactly one of these, and the UI is a function
 * of which:
 *
 *   IDLE        no call, or the last one is over
 *   OUTGOING    we invited and are waiting to be answered  (ringing, theirs)
 *   INCOMING    we were invited and have not answered      (ringing, ours)
 *   CONNECTING  answered on both sides; the room and the media are coming up
 *   CONNECTED   media is flowing
 *
 * The step from INCOMING or OUTGOING to CONNECTING is what starts the Janus
 * side: joining the room and publishing happen there, not on answer, because
 * the caller reaches CONNECTING when the callee's accept arrives. */
typedef enum {
    WFAV_STATE_IDLE       = 0,
    WFAV_STATE_OUTGOING   = 1,
    WFAV_STATE_INCOMING   = 2,
    WFAV_STATE_CONNECTING = 3,
    WFAV_STATE_CONNECTED  = 4,
} wfav_call_state_t;

const char *wfav_call_state_str(wfav_call_state_t state);

/* ------------------------------------------------------------ end reason */

/* callEndReason.js. These travel: a bye message carries one, and the receiver
 * maps it to its own point of view -- their Hangup is our RemoteHangup. The
 * mapping is in wfav_engine.c and is the reference's, table for table.
 *
 * The distinction worth keeping straight is local vs remote. REASON_* with no
 * prefix is something WE did or something that happened to US; the ones
 * spelled out (RemoteBusy, RemoteTimeout, ...) are the same event at the
 * other end. Showing "对方已挂断" for REASON_Hangup is the classic way to get
 * this backwards. */
typedef enum {
    WFAV_END_UNKNOWN                 = 0,
    WFAV_END_BUSY                    = 1,   /* we were already in a call */
    WFAV_END_SIGNAL_ERROR            = 2,
    WFAV_END_HANGUP                  = 3,   /* we hung up */
    WFAV_END_MEDIA_ERROR             = 4,
    WFAV_END_REMOTE_HANGUP           = 5,
    WFAV_END_OPEN_CAMERA_FAILURE     = 6,
    WFAV_END_TIMEOUT                 = 7,   /* we did not answer in time */
    WFAV_END_ACCEPT_BY_OTHER_CLIENT  = 8,   /* another of our clients took it */
    WFAV_END_ALL_LEFT                = 9,
    WFAV_END_REMOTE_BUSY             = 10,
    WFAV_END_REMOTE_TIMEOUT          = 11,  /* they did not answer in time */
    WFAV_END_REMOTE_NETWORK_ERROR    = 12,
    WFAV_END_ROOM_DESTROYED          = 13,
    WFAV_END_ROOM_NOT_EXIST          = 14,
    WFAV_END_ROOM_PARTICIPANTS_FULL  = 15,
    WFAV_END_INTERRUPTED             = 16,
    WFAV_END_REMOTE_INTERRUPTED      = 17,
    WFAV_END_KICKED                  = 18,
} wfav_end_reason_t;

/* A bye's reason is written from the SENDER's point of view, so it has to be
 * turned around before this end shows it: their Hangup is our RemoteHangup,
 * their Timeout is our RemoteTimeout. This is avenginekitImpl.js:186-235,
 * case for case.
 *
 * Getting it backwards does not break a call -- it puts the wrong sentence on
 * the screen, every time, which is worse in the way that only cosmetic bugs
 * shipped to every user are worse. It is a pure function of the enum, which
 * is why it lives with the enum and is what test/host tests first. */
wfav_end_reason_t wfav_end_reason_flip(wfav_end_reason_t reason);

/* A short Chinese phrase for the panel; never NULL. Written from the point of
 * view of the board, so REASON_HANGUP is "已挂断" and REMOTE_HANGUP is
 * "对方已挂断". */
const char *wfav_end_reason_str(wfav_end_reason_t reason);

/* ------------------------------------------------------ participant state */

/* Where one other person is, which is not the same question as where the
 * CALL is.
 *
 * These were wfav_call_state_t for a while, and the two lifecycles do not fit
 * in one enum: a participant is never IDLE, and CONNECTED means "media is
 * flowing" for a call and would have to mean "in the room" for someone who has
 * arrived and published nothing. Reusing the type made an attendee read as
 * connected, which is exactly the sentence a call screen must not print.
 *
 * The progression is one-way per room visit. Someone who stops publishing
 * goes back to JOINED and may reach PUBLISHING again. */
typedef enum {
    /* Invited and ringing, or answered but not yet in the room. Nothing about
     * them is observable from the room yet. */
    WFAV_PARTICIPANT_INVITED = 0,
    /* In the room, publishing nothing -- Janus calls this an attendee. They
     * are in the list and they are silent. */
    WFAV_PARTICIPANT_JOINED,
    /* Publishing, and we have asked for their audio. There is a subscription
     * coming up; there is not yet any sound. */
    WFAV_PARTICIPANT_PUBLISHING,
    /* Their media is arriving here. This is the only state in which the
     * board can actually hear them. */
    WFAV_PARTICIPANT_CONNECTED,
} wfav_participant_state_t;

const char *wfav_participant_state_str(wfav_participant_state_t state);

/* --------------------------------------------------------- participants */

/* One other person in the call, as far as this board is concerned.
 *
 * participantProfile.js, minus the video fields there is no video for. The
 * timestamps are the server's milliseconds, like every other WFC timestamp:
 * `join_time` is when they were invited, `accept_time` when they answered,
 * and the gap between them is what the ringing timeout is measured against.
 *
 * There is no separate `audience` flag: the state says it. Anyone below
 * PUBLISHING is in the room and silent. */
typedef struct {
    char                     user_id[WFC_TARGET_MAX];
    wfav_participant_state_t state;
    int64_t                  join_time;
    int64_t                  accept_time;
    bool                     audio_muted;
} wfav_participant_t;

#ifdef __cplusplus
}
#endif

#endif /* WFAV_TYPES_H */
