#!/usr/bin/env python3
"""Regenerates main/ui_pinyin_dict.c -- the IME's pinyin table.

LVGL ships a pinyin dictionary with its IME widget and it cannot be used here:
321 syllables of *traditional* Chinese, sized to match the demo font. Typing
"xie" on it offers 謝, and "ti" offers 題. For a mainland IM client that is not
a small dictionary, it is the wrong language.

So this builds one from the same character set the font covers -- GB2312 level
1 -- with two data sources that are already on hand:

  pypinyin  readings, heteronyms included, so 行 appears under both xing
            and hang. Heteronyms are ranked below primary readings, though:
            pypinyin knows archaic ones too -- it will tell you 接 can be
            read xie -- and a frequent character with a rare reading would
            otherwise crowd out the characters that really are spelled that
            way
  jieba     its word-frequency dictionary, summed per character, which is
            what orders the candidates. Ordering is the whole difference
            between an IME and a lookup table: everyone types "wo" expecting
            我 first, and nobody pages through 30 candidates to find it

Output format is LVGL's lv_pinyin_dict_t: {pinyin, candidates} pairs, sorted
by pinyin, NULL-terminated. The sort is load-bearing -- lv_ime_pinyin.c indexes
the table by first letter and assumes the entries for each letter are
contiguous and ascending.

    pip install pypinyin jieba && python3 tools/make_pinyin.py
"""

import collections
import os
import sys

# Relative to this script, not to the working directory -- see check_font.py.
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "main", "ui_pinyin_dict.c")

HEADER = '''/* The IME's pinyin table -- GENERATED by tools/make_pinyin.py, do not edit.
 *
 * LVGL's own dictionary is traditional Chinese (typing "xie" offers 謝), so
 * this replaces it: %(syllables)d syllables over the %(chars)d characters of GB2312
 * level 1, which is exactly what components/wfc_font/ can draw. Candidates are
 * ordered by how common the character is, from jieba's word-frequency
 * dictionary -- "wo" has to put 我 first or the IME is a lookup table.
 *
 * Sorted by pinyin, and that matters: lv_ime_pinyin.c indexes the table by
 * first letter and walks forward, so the entries for each letter have to be
 * contiguous and ascending.
 *
 * %(bytes)d bytes of flash, which is why the whole set is here rather than some
 * abridged version of it.
 */

#include "ui_pinyin_dict.h"

const lv_pinyin_dict_t ui_pinyin_dict[] = {
'''


def main():
    try:
        from pypinyin import Style, pinyin
        import jieba
    except ImportError as exc:
        sys.exit(f"{exc}. Try: pip install pypinyin jieba")

    # Character frequency, summed over jieba's word list. A character in many
    # frequent words is a frequent character.
    freq = collections.Counter()
    dict_txt = os.path.join(os.path.dirname(jieba.__file__), "dict.txt")
    with open(dict_txt, encoding="utf-8") as fh:
        for line in fh:
            parts = line.split()
            if len(parts) >= 2 and parts[1].isdigit():
                for ch in parts[0]:
                    freq[ch] += int(parts[1])

    # GB2312 level 1: the same set the font holds.
    chars = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                chars.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass

    table = collections.defaultdict(list)
    primary = {}
    for ch in chars:
        primary[ch] = pinyin(ch, style=Style.NORMAL)[0][0]
        readings = pinyin(ch, style=Style.NORMAL, heteronym=True)
        for syllable in {r for group in readings for r in group}:
            if syllable.isalpha() and syllable.isascii():
                table[syllable].append(ch)

    # Nothing starts with i, u or v; lv_ime_pinyin.c rejects those outright.
    for bad in ("i", "u", "v"):
        table.pop(bad, None)

    body = []
    total = 0
    for syllable in sorted(table):
        cands = sorted(set(table[syllable]),
                       key=lambda c: (primary[c] != syllable, -freq[c]))
        joined = "".join(cands)
        total += len(syllable) + 1 + len(joined.encode("utf-8")) + 1
        body.append(f'    {{ "{syllable}", "{joined}" }},\n')

    text = HEADER % {"syllables": len(table), "chars": len(chars),
                     "bytes": total} + "".join(body) + \
        "    { NULL, NULL },\n};\n"

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"{OUT}: {len(table)} syllables, {len(chars)} characters, "
          f"~{total / 1024:.1f} KB of string data")


if __name__ == "__main__":
    main()
